tp/exercise rails/group_03/config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :computer_infos
  get '/B_21_Roberta_Netzovarooms/', to: 'computer_infos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tp/exercise rails/group_03/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tp/exercise rails/group_03/app/models/computer_info.rb
class ComputerInfo < ApplicationRecord
	validates :room_id, uniqueness: true
	validates :processor, uniqueness: true
	belongs_to:room
end

tp/exercise rails/group_03/app/models/room.rb
class Room < ApplicationRecord
	has_many:computers
end

tp/exercise rails/group_03/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tp/exercise rails/group_03/app/controllers/computer_infos_controller.rb
class ComputerInfosController < ApplicationController
  before_action :set_computer_info, only: [:show, :edit, :update, :destroy]

  # GET /computer_infos
  # GET /computer_infos.json
  def index
    @computer_infos = ComputerInfo.all
    @rooms = Room.all
  end

  # GET /computer_infos/1
  # GET /computer_infos/1.json
  def show
  end

  # GET /computer_infos/new
  def new
    @computer_info = ComputerInfo.new
  end

  # GET /computer_infos/1/edit
  def edit
  end

  # POST /computer_infos
  # POST /computer_infos.json
  def create
    @computer_info = ComputerInfo.new(computer_info_params)

    respond_to do |format|
      if @computer_info.save
        format.html { redirect_to @computer_info, notice: 'Computer info was successfully created.' }
        format.json { render :show, status: :created, location: @computer_info }
      else
        format.html { render :new }
        format.json { render json: @computer_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computer_infos/1
  # PATCH/PUT /computer_infos/1.json
  def update
    respond_to do |format|
      if @computer_info.update(computer_info_params)
        format.html { redirect_to @computer_info, notice: 'Computer info was successfully updated.' }
        format.json { render :show, status: :ok, location: @computer_info }
      else
        format.html { render :edit }
        format.json { render json: @computer_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computer_infos/1
  # DELETE /computer_infos/1.json
  def destroy
    @computer_info.destroy
    respond_to do |format|
      format.html { redirect_to computer_infos_url, notice: 'Computer info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer_info
      @computer_info = ComputerInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_info_params
      params.require(:computer_info).permit(:color, :brand, :processor, :room_id)
    end
end

tp/exercise rails/group_03/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
 def index
    @computer_infos = ComputerInfo.all
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number, :room_size)
    end
end

tp/exercise rails/group_03/app/helpers/application_helper.rb
module ApplicationHelper
end

tp/exercise rails/group_03/app/helpers/computer_infos_helper.rb
module ComputerInfosHelper
end

tp/exercise rails/group_03/app/helpers/rooms_helper.rb
module RoomsHelper
end

tp/exercise rails/group_03/app/views/computer_infos/_form.html.erb
<%= form_with(model: computer_info, local: true) do |form| %>
  <% if computer_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(computer_info.errors.count, "error") %> prohibited this computer_info from being saved:</h2>

      <ul>
      <% computer_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :computer_info_color %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :computer_info_brand %>
  </div>

  <div class="field">
    <%= form.label :processor %>
    <%= form.text_field :processor, id: :computer_info_processor %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id, id: :computer_info_room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/exercise rails/group_03/app/views/computer_infos/edit.html.erb
<h1>Editing Computer Info</h1>

<%= render 'form', computer_info: @computer_info %>

<%= link_to 'Show', @computer_info %> |
<%= link_to 'Back', computer_infos_path %>

tp/exercise rails/group_03/app/views/computer_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Computer Infos</h1>

<table>
  <thead>
    <tr>
	<th>Color</th>
	<th>Brand</th>
	<th>Processor</th>
      	<th>Room number</th>
	<th>Room size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @computer_infos.each do |computer_info| %>
      <tr>
        <td><%= computer_info.color %></td>
        <td><%= computer_info.brand %></td>
        <td><%= computer_info.processor %></td>
        <td><%= computer_info.room.room_number %></td>
	<td><%= computer_info.room.room_size %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

tp/exercise rails/group_03/app/views/computer_infos/new.html.erb
<h1>New Computer Info</h1>

<%= render 'form', computer_info: @computer_info %>

<%= link_to 'Back', computer_infos_path %>

tp/exercise rails/group_03/app/views/computer_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @computer_info.color %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @computer_info.brand %>
</p>

<p>
  <strong>Processor:</strong>
  <%= @computer_info.processor %>
</p>

<p>
  <strong>Room:</strong>
  <%= @computer_info.room_id %>
</p>

<%= link_to 'Edit', edit_computer_info_path(@computer_info) %> |
<%= link_to 'Back', computer_infos_path %>

tp/exercise rails/group_03/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Computer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tp/exercise rails/group_03/app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_number %>
    <%= form.number_field :room_number, id: :room_room_number %>
  </div>

  <div class="field">
    <%= form.label :room_size %>
    <%= form.number_field :room_size, id: :room_room_size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/exercise rails/group_03/app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

tp/exercise rails/group_03/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Room size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.room_size %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

tp/exercise rails/group_03/app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

tp/exercise rails/group_03/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Room size:</strong>
  <%= @room.room_size %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>