tp/methods_rails/first_example/config/routes.rb
Rails.application.routes.draw do
  resources :user_subscriptions
  resources :subscriptions
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tp/methods_rails/first_example/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tp/methods_rails/first_example/app/models/subscription.rb
class Subscription < ApplicationRecord
	has_many:user_subscriptions
	has_many:users,  through: :user_subscriptions
end

tp/methods_rails/first_example/app/models/user.rb
class User < ApplicationRecord
	has_many:user_subscriptions
	has_many:subscriptions,  through: :user_subscriptions
end

tp/methods_rails/first_example/app/models/user_subscription.rb
class UserSubscription < ApplicationRecord
	belongs_to :user
	belongs_to :subscription
	validate :price_limits
	
	
		def price_limits
			t = 0
			s = 0
			if self.subscription.price < 10
				self.subscription.user_subscriptions.each do |user_subscription|
					if user_subscription.type_of == "Teacher"
						t += 1
					end
					if user_subscription.type_of == "Student"
						s += 1
					end
					if t >= 2 || s >= 10
					errors.add(self.type_of, "Cannot create another subscription user")
					end
				end
			end
		end

end

tp/methods_rails/first_example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tp/methods_rails/first_example/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:price)
    end
end

tp/methods_rails/first_example/app/controllers/user_subscriptions_controller.rb
class UserSubscriptionsController < ApplicationController
  before_action :set_user_subscription, only: [:show, :edit, :update, :destroy]

  # GET /user_subscriptions
  # GET /user_subscriptions.json
  def index
    	@user_subscriptions = UserSubscription.all
	@users = User.all
	@subscriptions = Subscription.all
  end

  # GET /user_subscriptions/1
  # GET /user_subscriptions/1.json
  def show
  end

  # GET /user_subscriptions/new
  def new
    @user_subscription = UserSubscription.new
  end

  # GET /user_subscriptions/1/edit
  def edit
  end

  # POST /user_subscriptions
  # POST /user_subscriptions.json
  def create
    @user_subscription = UserSubscription.new(user_subscription_params)

    respond_to do |format|
      if @user_subscription.save
        format.html { redirect_to @user_subscription, notice: 'User subscription was successfully created.' }
        format.json { render :show, status: :created, location: @user_subscription }
      else
        format.html { render :new }
        format.json { render json: @user_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_subscriptions/1
  # PATCH/PUT /user_subscriptions/1.json
  def update
    respond_to do |format|
      if @user_subscription.update(user_subscription_params)
        format.html { redirect_to @user_subscription, notice: 'User subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_subscription }
      else
        format.html { render :edit }
        format.json { render json: @user_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_subscriptions/1
  # DELETE /user_subscriptions/1.json
  def destroy
    @user_subscription.destroy
    respond_to do |format|
      format.html { redirect_to user_subscriptions_url, notice: 'User subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_subscription
      @user_subscription = UserSubscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_subscription_params
      params.require(:user_subscription).permit(:user_id, :subscription_id, :type_of)
    end
end

tp/methods_rails/first_example/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

tp/methods_rails/first_example/app/helpers/application_helper.rb
module ApplicationHelper
end

tp/methods_rails/first_example/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

tp/methods_rails/first_example/app/helpers/user_subscriptions_helper.rb
module UserSubscriptionsHelper
end

tp/methods_rails/first_example/app/helpers/users_helper.rb
module UsersHelper
end

tp/methods_rails/first_example/app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :subscription_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/methods_rails/first_example/app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

tp/methods_rails/first_example/app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.price %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

tp/methods_rails/first_example/app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

tp/methods_rails/first_example/app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @subscription.price %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>

tp/methods_rails/first_example/app/views/user_subscriptions/_form.html.erb
<%= form_with(model: user_subscription, local: true) do |form| %>
  <% if user_subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_subscription.errors.count, "error") %> prohibited this user_subscription from being saved:</h2>

      <ul>
      <% user_subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :user_subscription_user_id %>
  </div>

  <div class="field">
    <%= form.label :subscription_id %>
    <%= form.number_field :subscription_id, id: :user_subscription_subscription_id %>
  </div>

  <div class="field">
    <%= form.label :type_of %>
    <%= form.text_field :type_of, id: :user_subscription_type_of %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/methods_rails/first_example/app/views/user_subscriptions/edit.html.erb
<h1>Editing User Subscription</h1>

<%= render 'form', user_subscription: @user_subscription %>

<%= link_to 'Show', @user_subscription %> |
<%= link_to 'Back', user_subscriptions_path %>

tp/methods_rails/first_example/app/views/user_subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Subscription</th>
      <th>Type of</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_subscriptions.each do |user_subscription| %>
      <tr>
        <td><%= user_subscription.user_id %></td>
        <td><%= user_subscription.subscription_id %></td>
        <td><%= user_subscription.type_of %></td>
        <td><%= link_to 'Show', user_subscription %></td>
        <td><%= link_to 'Edit', edit_user_subscription_path(user_subscription) %></td>
        <td><%= link_to 'Destroy', user_subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Subscription', new_user_subscription_path %>

tp/methods_rails/first_example/app/views/user_subscriptions/new.html.erb
<h1>New User Subscription</h1>

<%= render 'form', user_subscription: @user_subscription %>

<%= link_to 'Back', user_subscriptions_path %>

tp/methods_rails/first_example/app/views/user_subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_subscription.user_id %>
</p>

<p>
  <strong>Subscription:</strong>
  <%= @user_subscription.subscription_id %>
</p>

<p>
  <strong>Type of:</strong>
  <%= @user_subscription.type_of %>
</p>

<%= link_to 'Edit', edit_user_subscription_path(@user_subscription) %> |
<%= link_to 'Back', user_subscriptions_path %>

tp/methods_rails/first_example/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/methods_rails/first_example/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

tp/methods_rails/first_example/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

tp/methods_rails/first_example/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

tp/methods_rails/first_example/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>